[template]
src = "collectd.tmpl"
dest = "/etc/collectd/collectd.conf"
owner = "root"
mode = "0644"
check_cmd = "/usr/sbin/collectd -C /etc/collectd/collectd.conf -t"
reload_cmd = "/usr/sbin/collectd -C /etc/collectd/collectd.conf -f"